### ISSUE TITLE
java.lang.LinkageError: loader constraint violation: when resolving method "lombok.launch....

### ISSUE THREAD

**Issue by Millz18** [rzwitserloot/lombok#1281]
Hello,
i recently installed lombok in Eclipse Lunar and one of my projects reports the following error:

`java.lang.LinkageError: loader constraint violation: when resolving method "lombok.launch.PatchFixesHider$Transform.transform_swapped(Lorg/eclipse/jdt/internal/compiler/ast/CompilationUnitDeclaration;Lorg/eclipse/jdt/internal/compiler/parser/Parser;)V" the class loader (instance of java/net/URLClassLoader) of the current class, org/eclipse/jdt/internal/compiler/parser/Parser, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, lombok/launch/PatchFixesHider$Transform, have different Class objects for the type org/eclipse/jdt/internal/compiler/ast/CompilationUnitDeclaration used in the signature (com.mysema.maven:apt-maven-plugin:1.1.2:process:annotations-generate-sources:generate-sources)

org.apache.maven.plugin.MojoExecutionException: java.lang.LinkageError: loader constraint violation: when resolving method "lombok.launch.PatchFixesHider$Transform.transform_swapped(Lorg/eclipse/jdt/internal/compiler/ast/CompilationUnitDeclaration;Lorg/eclipse/jdt/internal/compiler/parser/Parser;)V" the class loader (instance of java/net/URLClassLoader) of the current class, org/eclipse/jdt/internal/compiler/parser/Parser, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, lombok/launch/PatchFixesHider$Transform, have different Class objects for the type org/eclipse/jdt/internal/compiler/ast/CompilationUnitDeclaration used in the signature
	at com.mysema.maven.apt.AbstractProcessorMojo.execute(AbstractProcessorMojo.java:335)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.RuntimeException: java.lang.LinkageError: loader constraint violation: when resolving method "lombok.launch.PatchFixesHider$Transform.transform_swapped(Lorg/eclipse/jdt/internal/compiler/ast/CompilationUnitDeclaration;Lorg/eclipse/jdt/internal/compiler/parser/Parser;)V" the class loader (instance of java/net/URLClassLoader) of the current class, org/eclipse/jdt/internal/compiler/parser/Parser, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, lombok/launch/PatchFixesHider$Transform, have different Class objects for the type org/eclipse/jdt/internal/compiler/ast/CompilationUnitDeclaration used in the signature
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at com.mysema.maven.apt.AbstractProcessorMojo.execute(AbstractProcessorMojo.java:327)
	... 32 more
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "lombok.launch.PatchFixesHider$Transform.transform_swapped(Lorg/eclipse/jdt/internal/compiler/ast/CompilationUnitDeclaration;Lorg/eclipse/jdt/internal/compiler/parser/Parser;)V" the class loader (instance of java/net/URLClassLoader) of the current class, org/eclipse/jdt/internal/compiler/parser/Parser, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, lombok/launch/PatchFixesHider$Transform, have different Class objects for the type org/eclipse/jdt/internal/compiler/ast/CompilationUnitDeclaration used in the signature
	at org.eclipse.jdt.internal.compiler.parser.Parser.endParse(Parser.java:9887)
	at org.eclipse.jdt.internal.core.util.CommentRecorderParser.endParse(CommentRecorderParser.java:116)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11059)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11283)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11240)
	at org.eclipse.jdt.internal.compiler.parser.Parser.dietParse(Parser.java:9660)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.parse(CompilationUnitResolver.java:507)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1202)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:809)
	at com.google.googlejavaformat.java.Formatter.format(Formatter.java:115)
	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:157)
	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:144)
	at dagger.internal.codegen.SourceFileGenerator.generate(SourceFileGenerator.java:77)
	at dagger.internal.codegen.ModuleProcessingStep.process(ModuleProcessingStep.java:132)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:318)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:171)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 35 more
`
Allthough this error occurs everything seems to build and run without any problems and i could also delombok files using a Maven goal.

Any ideas?

**Comment by rspilker** [comment]
What would help if you would also attach your pom file.

**Comment by rspilker** [comment]
Possibly this is fixed in the 1.16.14 release which will be shipped in a few days. Can you test this?

**Comment by Millz18** [comment]
The pom files in my case have a complex hierarchy. (first parent-pom has ca. 1000 lines the next parent-pom ca. 2500 lines and the poms itself have about 200 lines). Additionally i can not provide the whole files because it is not my own project. Are there maybe some relevant things you are looking for? Maybe the sections build-plugins or dependencyManagement?

Seems like the problem still occures in my Projects after installing Lombok 1.16.14. Lombok is not used in the Projects which are effected (and Lombok is also not included in the pom).

**Comment by Millz18** [comment]
I did some cleanup and now the problem seems not to appear at the moment. Looks like the version 1.16.14 fixes the problem

**Comment by Millz18** [comment]
I did some cleanup on the effected projects and now the problem seems not to appear anymore. 

Looks like the version 1.16.14 fixes the problem.
