### ISSUE TITLE
Lombok won't make project compile with the new gradle 3.2.0

### ISSUE THREAD

**Issue by iGio90** [rzwitserloot/lombok#1882]
Sup guys. Something is wrong with the new gradle 3.2.0.
As posted on Stackoverflow from this guy https://stackoverflow.com/questions/52606514/android-gradle-plugin-update-from-3-1-4-to-3-2-0-cause-taskexecutionexception 

something unknown is generating the error stated on the post.
I've then created a new test project, removed the dependencies one by one and stripped everything until i've figured out that the things causing the issue is lombok.

Here is the stripped module level gradle file:

```apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    buildToolsVersion "28.0.3"
    defaultConfig {
        applicationId "com.test"
        minSdkVersion 17
        targetSdkVersion 28
        versionCode 1
        versionName "1"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
        javaCompileOptions {
            annotationProcessorOptions {
                includeCompileClasspath true
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    dexOptions {
        preDexLibraries = false
        javaMaxHeapSize "2g"
        jumboMode true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
}

repositories{
    mavenCentral()
    maven {
        url 'https://jitpack.io'
    }
    maven { url 'http://dl.bintray.com/amulyakhare/maven' }
    maven { url 'https://maven.fabric.io/public' }
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    androidTestImplementation('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    //noinspection GradleCompatible
    implementation 'com.android.support:appcompat-v7:28.0.0'

    compileOnly 'org.projectlombok:lombok:1.18.2'
    annotationProcessor 'org.projectlombok:lombok:1.18.2'
    testImplementation 'junit:junit:4.12'
}
```
```

// So, if I leave compileOnly 'org.projectlombok:lombok:1.18.2' the following error occurs in compilation time:

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException
	at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
	at sun.reflect.GeneratedMethodAccessor655.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
	... 33 more
Caused by: com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.transform(DexArchiveBuilderTransform.java:427)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	... 48 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
	at com.android.ide.common.internal.WaitableExecutor.waitForTasksWithQuickFail(WaitableExecutor.java:146)
	at com.android.build.gradle.internal.transforms.DesugarIncrementalTransformHelper.getInitalGraphData(DesugarIncrementalTransformHelper.java:162)
	at com.android.build.gradle.internal.transforms.DesugarIncrementalTransformHelper.makeDesugaringGraph(DesugarIncrementalTransformHelper.java:130)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:160)
	at com.android.build.gradle.internal.transforms.DesugarIncrementalTransformHelper.getDependenciesPaths(DesugarIncrementalTransformHelper.java:231)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.getD8DesugaringCacheInfo(DexArchiveBuilderTransform.java:461)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.transform(DexArchiveBuilderTransform.java:375)
	... 51 more
Caused by: java.lang.RuntimeException
	at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:148)
	at org.objectweb.asm.ClassReader.readModule(ClassReader.java:731)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:632)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:144)
	at com.android.builder.desugaring.DesugaringClassAnalyzer.analyzeJar(DesugaringClassAnalyzer.java:92)
	at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:63)
	at com.android.build.gradle.internal.transforms.DesugarIncrementalTransformHelper.lambda$getInitalGraphData$4(DesugarIncrementalTransformHelper.java:150)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

If I remove it, everything runs fine. 
Thanks 👍

**Comment by castrogne** [comment]
Hi,

Same problem here...

Thanks,

**Comment by victorwss** [comment]
"*with the new gradle 3.2.0*"

Latest Gradle version is 4.10.2. Maybe your are refering to the Android gradle plugin?

**Comment by castrogne** [comment]
Yes, that's it. Android gradle plugin is now 3.2.0, with Gradle 4.6.

https://developer.android.com/studio/releases/gradle-plugin

The problem came with the gradle plugnin 3.2.0, version before is OK.

**Comment by samarthd** [comment]
I just discovered this was the issue after lots of frustrating guesswork on what was causing problems!!

Key takeaways:

- **This issue is present on all versions of Lombok starting with `1.16.22`.**
- The failure with the Android Gradle Plugin is caused by a change in the default settings in `3.2.0`.  If you look at the "Behavior Changes" list for `3.2.0` at the [link @castrogne posted](https://developer.android.com/studio/releases/gradle-plugin), you will see:  _"Desugaring with D8 is now enabled by default."_ You can actually get the same issue to occur on Android Gradle Plugin version `3.1.0` if you go into your `gradle.properties` and enter the property: `android.enableD8.desugaring=true`. 



**The current proper solution (recommended): downgrade to Lombok `1.16.18`. It works flawlessly.** 

**The hacky gross solution (not recommended):** If you _really_ don't want to downgrade Lombok for whatever reason, you can keep your Android Gradle Plugin at version `3.2.0` and put this in your `gradle.properties`: `android.enableD8.desugaring=false`. _This is not recommended, as even Google will warn you that setting this to false is experimental and unsupported._

I hope this helps any poor bastard like me who did _not_ get a detailed build error output...the failure was extremely vague and did not make any mention of Lombok being the root of the issue. I had to manually go through each commit in my history to figure out where things broke. Come to think of it, my Instant Run in Android Studio was being wonky after I updated Lombok back then (though it wasn't causing a full on build failure like it was after the D8 desugaring got enabled).

**Comment by Boehrsi** [comment]
Currently facing the same problem and recognized only with Java 8 enabled the problem occurs.
Removing the Java 8 compileOptions "fixes" the problem for me.
`    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }`

**Comment by castrogne** [comment]
Thanks, i'll have a try next monday, to downgrade lombok to 1.16.18.

But do you think next version of gradle will still be not compatible with gradle plugin for ever? We will be stuck to that version...

**Comment by samarthd** [comment]
@Boehrsi Yes, the reason for that is because _desugaring_ is the process of "back porting" Java 8 code to allow it to work more fluently with other libraries/utilities. If you did not use any Java 8 language features in your app to begin with, then then there would be no desugaring necessary.

**Comment by samarthd** [comment]
@castrogne I think you meant to write "do you think the next versions of the Android Gradle Plugin will not be compatible with _the latest Lombok versions_ forever" - and to answer that, I think yes, this behavior will remain an issue for the foreseeable future.

I don't know for sure, but my guess is that all versions of Lombok greater than `1.16.18` must be using some Java 8 language features that are not supported as described at [the documentation here](https://developer.android.com/studio/write/java8-support).

As you can see, it says 

> Android Studio provides built-in support for using certain Java 8 language features and third-party libraries that use them.
...
> Android Studio does not support all Java 8 language features, but more are being added in future releases of the IDE. 

It's possible that new versions of Lombok are using unsupported features and thus failing to compile properly.

**Comment by castrogne** [comment]
@samarthd Yes you've well understood what i wanted to say. So we're stuck with lombok 1.16.18...  You was realy clear, thanks for your explanations.

**Comment by janrieke** [comment]
Is there some minimal example somewhere? Then one could try to track the problem down to a specific commit. That could help finding a workaround.
However, it could still turn out that this simply cannot be fixed in lombok, but only by the Android tool chain.

**Comment by castrogne** [comment]
Well, it worked! Thanks!

The 2 solutions you spoke about : 

1- **The current proper solution (recommended):**  lombok V1.16.18 : 
When I changed lombok version, the @AllArgConstructor didn't worked anymore. And for any reason, I couldn't either use @RequiredArgsConstructor(suppressConstructorProperties = true) . The reason was method suppressConstructorProperties not found... After that problem, I also had "error: cannot find symbol class Generated"... So to solve all that, I had to do : 
  - lombok version to **1.1.6.18**
  - add a "lombok.config" file in project root, with the line `"lombok.anyConstructor.suppressConstructorProperties = true"`
  - add in my build.gradle 
`"compileOnly 'javax.annotation:jsr250-api:1.0'"`
  
  
2- **The hacky gross solution (not recommended),** use gradle.properties
Let all versions up to date (my lombok version was 1.18.2, gradle 4.6, gradle plugin 3.2.0) and add the following line to your gradle.properties : 
`android.enableD8.desugaring=false`
When syncing, you get the wargning "The option setting 'android.enableD8.desugaring=false' is experimental and unsupported. The current default is 'true'". But anyway, all build OK after that. 

Finaly, 
I don't know the future of that "desugaring false" option. But for now, it seems to have no impact for me... I think I will stay in that not recommanded way, and keep all my libs in up to date version. I'll just keep trace to that point in case of future change!

Thanks all!

Castrogne

**Comment by janrieke** [comment]
I think sticking to an old Lombok version should not be the solution.
After a bit of research, it looks to me that desugaring works with Lombok, but only the new integrated desugaring does not. The option `android.enableD8.desugaring=false` does not switch desugaring off, it just execute it as a separate step. So it more and more looks to me like a problem of the android tool chain.

**Comment by castrogne** [comment]
OK, I think too and that's why i just use desugaring=false for now, and i'll try to remove it for next versions.

Thanks,

**Comment by castrogne** [comment]
Hi guys,

I'm currently testing the solution with "desugaring=false". I could only test compile last sunday, not running. And the fact is that if I do some "clean" then "run" (without build before), the error is still there... If i do some "clean", then "build", then "run", it works.

So I agree, seems to be Android Studio Build sequence that causes the trouble... I keep working like that for now, and let you know if I have more troubles.

Regards,

**Comment by rspilker** [comment]
Lombok does not use java8 features.

**Comment by gavra0** [comment]
I've updated https://issuetracker.google.com/117374690 with information why this is happening, but pasting here as well for visibility.

This is indeed an issue with the Android Gradle plugin, and it has been fixed in 3.3.0-alpha01, as part of fixing the https://issuetracker.google.com/74428304. Soon, first 3.3 beta should be released, so if possible, please update to that version.

In more details, this issue occurs because Opcodes.ASM5 is used to initialize the `ClassVisitor` used to read module-info.class, which exists in e.g. [Lombok 1.18.2](https://mvnrepository.com/artifact/org.projectlombok/lombok/1.18.2). This results in RuntimeException, as Opcodes.ASM6 should be used instead. It happens both with `android.enableD8.desugaring=true|false`. To reproduce, run a clean build, add a print statement to the method body, and try to build again.

**Comment by janrieke** [comment]
Yep, that explains why 1.16.20 was the first to fail: a9c1d3d

**Comment by rspilker** [comment]
Will be fixed in the Android Gradle Plugin 3.3.0.

**Comment by softboy99** [comment]
this is closed.Has it be fixed? i test it with latest 3.3.0 RC2 and Lombok 1.18.4, still failed

**Comment by Maaartinus** [comment]
@softboy99 As stated above, this has been or will be fixed elsewhere. [The Android/Gradle guys claim](https://issuetracker.google.com/issues/117374690#comment4), it has been fixed, so you may want to report back to them.
